/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package applic_point_presse;

import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.text.DateFormat;
import java.util.Date;
import java.util.Enumeration;
import java.util.Locale;
import java.util.Properties;
import java.util.TimeZone;
import java.util.Vector;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import network.NetworkBasicClient;
import network.NetworkBasicServer;

/**
 *
 * @author Kevin
 */
public class Applic_Point_Presse extends javax.swing.JFrame {

    /**
     * Creates new form Applic_Point_Presse
     */
    NetworkBasicServer server;
    NetworkBasicClient client;
    DefaultTableModel dtm;
    Vector news = new Vector();
    Date dateApplic;
    
    public Applic_Point_Presse() {
        initComponents();
        server=new NetworkBasicServer(60002,jCheckBoxNews);
        client=new NetworkBasicClient("localhost", 60001);
        
        this.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent windowEvent) {
                client.setEndSending();
            }
        });
        
        // grouper radiobutton
        ButtonGroup buttonGroupPreferences = new ButtonGroup();
        buttonGroupPreferences.add(jRadioButtonInternational);
        buttonGroupPreferences.add(jRadioButtonPolitique);
        buttonGroupPreferences.add(jRadioButtonRagots);
        buttonGroupPreferences.add(jRadioButtonSports);
        
        dtm = (DefaultTableModel) jTableNews.getModel();
        
        dateApplic = new Date();
        String datef = readConfigProperties();
        String [] split = datef.split("-");
        Locale varloc=Locale.ROOT;
        switch(Integer.parseInt(split[2]))
        {
            case 0:
                varloc = Locale.FRANCE;
                break;
            case 1:
                varloc = Locale.UK;
                break;
            case 2:
                varloc = Locale.GERMANY;
                break;
            case 3:
                varloc = Locale.ITALY;
                break;
            case 4:
                varloc = Locale.US;
                break;
        }
        DateFormat dateFormat = DateFormat.getDateTimeInstance(Integer.parseInt(split[0]),Integer.parseInt(split[1]),varloc);
        if(varloc==Locale.US)
            dateFormat.setTimeZone(TimeZone.getTimeZone("PST"));
        else if(varloc==Locale.UK)
            dateFormat.setTimeZone(TimeZone.getTimeZone("Europe/London"));
        jLabelDate.setText(dateFormat.format(dateApplic));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonEnvoi = new javax.swing.JButton();
        jButtonSave = new javax.swing.JButton();
        jCheckBoxImportant = new javax.swing.JCheckBox();
        jTextFieldJournaliste = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldTitre = new javax.swing.JTextField();
        jLabelReponse = new javax.swing.JLabel();
        jTextFieldTexte = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButtonAnnuler = new javax.swing.JButton();
        jLabelNombreNews = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableNews = new javax.swing.JTable();
        jRadioButtonPolitique = new javax.swing.JRadioButton();
        jRadioButtonInternational = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jRadioButtonSports = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaLogEvent = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jRadioButtonRagots = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jCheckBoxNews = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jLabelNbNews = new javax.swing.JLabel();
        jLabelDate = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonEnvoi.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButtonEnvoi.setText("Envoyer");
        jButtonEnvoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnvoiActionPerformed(evt);
            }
        });

        jButtonSave.setText("Enregistrer");
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });

        jCheckBoxImportant.setText("Important");

        jLabel4.setText("Réponse :");

        jLabelReponse.setText("---");

        jLabel6.setText("Nombre de news envoyés durant cette session :");

        jButtonAnnuler.setText("Annuler");

        jTableNews.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "News", "Type", "Important ?", "Journaliste"
            }
        ));
        jTableNews.setName(""); // NOI18N
        jScrollPane1.setViewportView(jTableNews);

        jRadioButtonPolitique.setText("Politique");

        jRadioButtonInternational.setSelected(true);
        jRadioButtonInternational.setText("International");

        jLabel8.setText("Log des événements :");

        jRadioButtonSports.setText("Sports");

        jTextAreaLogEvent.setColumns(20);
        jTextAreaLogEvent.setRows(5);
        jScrollPane2.setViewportView(jTextAreaLogEvent);

        jLabel1.setText("Journaliste :");

        jRadioButtonRagots.setText("Ragots et potins");

        jLabel2.setText("Titre :");

        jCheckBoxNews.setText("News envoyée");
        jCheckBoxNews.setEnabled(false);

        jLabel3.setText("Texte :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldTexte, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldTitre, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldJournaliste, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBoxImportant)
                            .addComponent(jRadioButtonRagots)
                            .addComponent(jRadioButtonPolitique)
                            .addComponent(jRadioButtonSports)
                            .addComponent(jRadioButtonInternational))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBoxNews)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jButtonEnvoi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonAnnuler, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabelReponse)
                            .addComponent(jLabel4)))
                    .addComponent(jLabelDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelNbNews, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelNombreNews, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel8)
                            .addComponent(jScrollPane2)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 428, Short.MAX_VALUE))
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonSave)
                        .addGap(37, 37, 37))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTextFieldJournaliste, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextFieldTitre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextFieldTexte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabelNombreNews, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelNbNews, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jRadioButtonInternational)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButtonPolitique)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButtonSports)
                        .addGap(2, 2, 2)
                        .addComponent(jRadioButtonRagots)
                        .addGap(22, 22, 22)
                        .addComponent(jCheckBoxImportant))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(44, 44, 44)
                                        .addComponent(jLabel8))
                                    .addComponent(jButtonSave))
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonAnnuler)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonEnvoi)
                                .addGap(18, 18, 18)
                                .addComponent(jCheckBoxNews)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelReponse)))))
                .addGap(18, 18, 18)
                .addComponent(jLabelDate, javax.swing.GroupLayout.DEFAULT_SIZE, 16, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private String readConfigProperties() {
        String separator = System.getProperty("file.separator");
        String home = System.getProperty("user.dir");
        String chemin = ".." + separator + "Applic_Salle_Presse" + separator + "src" + separator + "applic_salle_presse" + separator + "config.properties";
        String value = "";
        try {
            FileInputStream in = new FileInputStream(chemin);
            Properties props = new Properties();
            props.load(in);
            Enumeration<?> e = props.propertyNames();
            while (e.hasMoreElements()) {
                String key = (String) e.nextElement();
                if ("Date".equals(key)) {
                    value = props.getProperty(key);
                }
            }
            in.close();
        } catch (FileNotFoundException e) {
            System.out.println("Fichier de configuration non trouvé !");
        } catch (IOException e) {
            System.out.println("Erreur : " + e.getMessage());
        }
        return value;
    }
    
    private void jButtonEnvoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnvoiActionPerformed
        if(!jLabelNbNews.getText().equals("0"))
        {
            String com = jTextFieldTitre.getText();
            String envoiMessage = client.sendString(com);
            if(!envoiMessage.isEmpty())
            {
                jCheckBoxNews.setSelected(true);
                jLabelReponse.setText(envoiMessage+" !!!");
            }
        }
        else
            JOptionPane.showMessageDialog(this, "Pas de news a envoyé", "Info", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_jButtonEnvoiActionPerformed

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        String nomJournaliste,titre;
        nomJournaliste = jTextFieldJournaliste.getText();
        titre = jTextFieldTitre.getText();
        if(!titre.isEmpty()&&!nomJournaliste.isEmpty())
        {
            String com,cat,imp;
            com = jTextFieldTexte.getText();
            
            if(jRadioButtonInternational.isSelected())
                cat = "Internationales";
            else if(jRadioButtonPolitique.isSelected())
                cat = "Politique";
            else if(jRadioButtonSports.isSelected())
                cat = "Sports";
            else
                cat = "Ragots";
            
            if(jCheckBoxImportant.isSelected())
                imp ="Y";
            else
                imp = "N";
            jTextFieldJournaliste.setText("");
            jTextFieldTitre.setText("");
            jTextFieldTexte.setText("");
            jRadioButtonInternational.setSelected(true);
            jCheckBoxImportant.setSelected(false);
            dtm.addRow(new Object[]{titre, cat, imp, nomJournaliste});
            news.add(titre);
            news.add(cat);
            news.add(imp);
            news.add(nomJournaliste);
            //int hour = (int)(dateApplic.getTime() % 86400000) / 3600000;
            //news.add(hour);
        }
        else
            JOptionPane.showMessageDialog(this, "Encoder une news", "Info", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_jButtonSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Applic_Point_Presse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Applic_Point_Presse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Applic_Point_Presse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Applic_Point_Presse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Applic_Point_Presse().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAnnuler;
    private javax.swing.JButton jButtonEnvoi;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JCheckBox jCheckBoxImportant;
    private javax.swing.JCheckBox jCheckBoxNews;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelDate;
    private javax.swing.JLabel jLabelNbNews;
    private javax.swing.JLabel jLabelNombreNews;
    private javax.swing.JLabel jLabelReponse;
    private javax.swing.JRadioButton jRadioButtonInternational;
    private javax.swing.JRadioButton jRadioButtonPolitique;
    private javax.swing.JRadioButton jRadioButtonRagots;
    private javax.swing.JRadioButton jRadioButtonSports;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableNews;
    private javax.swing.JTextArea jTextAreaLogEvent;
    private javax.swing.JTextField jTextFieldJournaliste;
    private javax.swing.JTextField jTextFieldTexte;
    private javax.swing.JTextField jTextFieldTitre;
    // End of variables declaration//GEN-END:variables
}
