/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package applic_salle_presse;

import java.awt.*;
import java.util.*;
import javax.swing.*;

/**
 *
 * @author Kevin
 */
public class JDialogTraitementNews extends javax.swing.JDialog {

    /**
     * Creates new form JDialogTraitementNews
     */
    ButtonGroup buttonGroupPreferences = new ButtonGroup();
    public News n;
    public boolean ok;
    private Journaliste nomJ;
    private Vector<String> motcle;
    public JDialogTraitementNews(java.awt.Frame parent, boolean modal, String titreNews,Journaliste nomJournaliste) {
        super(parent, modal);
        initComponents();
        
        // centrer fenetre
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        
        //regrouper radio button
        buttonGroupPreferences.add(jRadioButtonInter);
        buttonGroupPreferences.add(jRadioButtonPolitique);
        buttonGroupPreferences.add(jRadioButtonRagot);
        buttonGroupPreferences.add(jRadioButtonSports);
        
        jLabelNomNews.setText(titreNews);
        jRadioButtonInter.setSelected(true);
        nomJ = nomJournaliste;
    }
    public JDialogTraitementNews(java.awt.Frame parent, boolean modal,News news) {
        super(parent, modal);
        initComponents();
        
        // centrer fenetre
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        
        //regrouper radio button
        buttonGroupPreferences.add(jRadioButtonInter);
        buttonGroupPreferences.add(jRadioButtonPolitique);
        buttonGroupPreferences.add(jRadioButtonRagot);
        buttonGroupPreferences.add(jRadioButtonSports);
        
        jLabelNomNews.setText(news.getTitre());
        if(news.getCategorie()==Categorie.INTERNATIONAL)
            jRadioButtonInter.setSelected(true);
        else if(news.getCategorie()==Categorie.POLITIQUE)
            jRadioButtonPolitique.setSelected(true);
        else if(news.getCategorie()==Categorie.SPORT)
            jRadioButtonSports.setSelected(true);
        else
            jRadioButtonRagot.setSelected(true);
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        if(news.getMotCle()!=null)
            model = new DefaultComboBoxModel(news.getMotCle());
        jComboBoxMotCle.setModel(model);
        jTextAreaCom.setText(news.getTexte());
        nomJ=news.getJournaliste();
        jCheckBoxImp.setSelected(news.getImportant());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabelNomNews = new javax.swing.JLabel();
        jRadioButtonInter = new javax.swing.JRadioButton();
        jRadioButtonPolitique = new javax.swing.JRadioButton();
        jRadioButtonSports = new javax.swing.JRadioButton();
        jRadioButtonRagot = new javax.swing.JRadioButton();
        jCheckBoxImp = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldMotCle = new javax.swing.JTextField();
        jButtonAddMotCle = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxMotCle = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaCom = new javax.swing.JTextArea();
        jButtonOk = new javax.swing.JButton();
        jButtonAnnuler = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("news :");

        jRadioButtonInter.setText("Internationales");

        jRadioButtonPolitique.setText("Vie politique");

        jRadioButtonSports.setText("Infos sports");

        jRadioButtonRagot.setText("Ragot et potins");

        jCheckBoxImp.setText("Important");

        jLabel3.setText("Mot clé :");

        jButtonAddMotCle.setText("+");
        jButtonAddMotCle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddMotCleActionPerformed(evt);
            }
        });

        jLabel4.setText("Mots clé :");

        jLabel5.setText("Commentaires :");

        jTextAreaCom.setColumns(20);
        jTextAreaCom.setRows(5);
        jScrollPane1.setViewportView(jTextAreaCom);

        jButtonOk.setText("Ok");
        jButtonOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOkActionPerformed(evt);
            }
        });

        jButtonAnnuler.setText("Annuler");
        jButtonAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnnulerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBoxImp)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(31, 31, 31)
                                        .addComponent(jLabelNomNews, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(59, 59, 59)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jRadioButtonInter)
                                                        .addGap(54, 54, 54)
                                                        .addComponent(jRadioButtonPolitique))
                                                    .addComponent(jTextFieldMotCle, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(52, 52, 52)
                                                        .addComponent(jRadioButtonSports))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(40, 40, 40)
                                                        .addComponent(jButtonAddMotCle)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(jLabel4))))
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jRadioButtonRagot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBoxMotCle, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(258, 258, 258)
                        .addComponent(jButtonOk)
                        .addGap(38, 38, 38)
                        .addComponent(jButtonAnnuler)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabelNomNews, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonPolitique)
                    .addComponent(jRadioButtonInter)
                    .addComponent(jRadioButtonSports)
                    .addComponent(jRadioButtonRagot))
                .addGap(18, 18, 18)
                .addComponent(jCheckBoxImp)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldMotCle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAddMotCle)
                    .addComponent(jLabel4)
                    .addComponent(jComboBoxMotCle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonOk)
                    .addComponent(jButtonAnnuler))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOkActionPerformed
        String com = jTextAreaCom.getText();
        String titreNews = jLabelNomNews.getText();
        Categorie nomCat;
        if(jRadioButtonInter.isSelected())
            nomCat = Categorie.INTERNATIONAL;
        else if(jRadioButtonPolitique.isSelected())
            nomCat = Categorie.POLITIQUE;
        else if(jRadioButtonSports.isSelected())
            nomCat = Categorie.SPORT;
        else
            nomCat = Categorie.POTIN;
        
        if(jComboBoxMotCle.getItemCount()==0&&!jTextFieldMotCle.getText().isEmpty())
        {
            String[] splitmot;
            splitmot=jTextFieldMotCle.getText().split("[-\\/]");

            motcle = new Vector<String>(Arrays.asList(splitmot));
        }
        else if(!jTextFieldMotCle.getText().isEmpty()&&jComboBoxMotCle.getItemCount()>0)
        {
            motcle = new Vector<String>();
            String[] splitmot;
            splitmot=jTextFieldMotCle.getText().split("[-\\/]");
            for(int i=0; i < splitmot.length;i++)
                motcle.add(splitmot[i]);
            ComboBoxModel model = jComboBoxMotCle.getModel();
            Vector m = new Vector();
            for(int i = 0; i < model.getSize(); i++) {
                motcle.add(model.getElementAt(i).toString());
            }
        }
        else
        {
            ComboBoxModel model = jComboBoxMotCle.getModel();
            Vector m = new Vector();
            for(int i = 0; i < model.getSize(); i++) {
                m.add(model.getElementAt(i).toString());
            }
            motcle = new Vector<String>(m);
        }
        n = new News(titreNews,com,nomCat,nomJ,new Date(),jCheckBoxImp.isSelected(),motcle);
        ok=true;
        this.setVisible(false);
    }//GEN-LAST:event_jButtonOkActionPerformed

    private void jButtonAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnnulerActionPerformed
        ok=false;
        this.setVisible(false);
    }//GEN-LAST:event_jButtonAnnulerActionPerformed

    private void jButtonAddMotCleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddMotCleActionPerformed
        String[] splitmot;
        splitmot=jTextFieldMotCle.getText().split("[-\\/]");
        for(String s : splitmot)
            jComboBoxMotCle.addItem(s);
        jTextFieldMotCle.setText("");
        motcle = new Vector<String>(Arrays.asList(splitmot));
    }//GEN-LAST:event_jButtonAddMotCleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialogTraitementNews.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialogTraitementNews.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialogTraitementNews.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialogTraitementNews.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog 
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDialogTraitementNews dialog = new JDialogTraitementNews(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddMotCle;
    private javax.swing.JButton jButtonAnnuler;
    private javax.swing.JButton jButtonOk;
    private javax.swing.JCheckBox jCheckBoxImp;
    private javax.swing.JComboBox<String> jComboBoxMotCle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelNomNews;
    private javax.swing.JRadioButton jRadioButtonInter;
    private javax.swing.JRadioButton jRadioButtonPolitique;
    private javax.swing.JRadioButton jRadioButtonRagot;
    private javax.swing.JRadioButton jRadioButtonSports;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaCom;
    private javax.swing.JTextField jTextFieldMotCle;
    // End of variables declaration//GEN-END:variables
}
